SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Goal Dimensions
GOAL_WIDTH = 600
GOAL_HEIGHT = 200 # Height from ground up
GROUND_Y = SCREEN_HEIGHT - 50
GOAL_TOP_Y = GROUND_Y - GOAL_HEIGHT
GOAL_LEFT_X = (SCREEN_WIDTH - GOAL_WIDTH) // 2
GOAL_RIGHT_X = GOAL_LEFT_X + GOAL_WIDTH
